"""Seed data for questionnaire table."""
from typing import Any, Dict, List


def get_questionnaire_seeds() -> List[Dict[str, Any]]:
    """Return seed questionnaire definitions."""
    return [
        {
            "questionnaire_id": "health-basic",
            "title": "基础健康信息问卷",
            "description": "所有病种洞察的基础健康信息采集问卷（性别、年龄、身高、体重等）",
            "skill_name": None,
            "version": 1,
            "created_by": "system",
            "updated_by": "system",
            "questions": [
                {
                    "id": "intro_module1",
                    "type": "intro",
                    "required": False,
                    "behavior": {"autoNext": True, "autoNextDelay": 2000},
                    "introImageSrc": "https://iobs.pingan.com.cn/download/pah-ows-dmz-prd/54216111800447f988bde78c3de99750",
                    "hasPrev": False,
                    "hasNext": False,
                    "currentIndex": None,
                    "totalQs": None,
                    "prevQuestionId": None,
                    "nextQuestionId": "gender-select",
                    "showNavigation": False,
                },
                {
                    "id": "gender-select",
                    "type": "single",
                    "componentType": "image",
                    "title": "请选择您的性别",
                    "required": True,
                    "options": [
                        {"value": "male", "label": "男性", "image": "https://via.placeholder.com/200x200/4A90E2/FFFFFF?text=男性"},
                        {"value": "female", "label": "女性", "image": "https://via.placeholder.com/200x200/E91E63/FFFFFF?text=女性"},
                    ],
                    "hasPrev": False,
                    "hasNext": True,
                    "currentIndex": 1,
                    "totalQs": 4,
                    "prevQuestionId": "intro_start",
                    "nextQuestionId": "q_age_picker",
                    "showNavigation": True,
                },
                {
                    "id": "q_age_picker",
                    "type": "number",
                    "componentType": "numberPicker",
                    "title": "请选择您的年龄",
                    "required": True,
                    "min": 1,
                    "max": 120,
                    "defaultValue": 18,
                    "hasPrev": True,
                    "hasNext": True,
                    "currentIndex": 2,
                    "totalQs": 4,
                    "prevQuestionId": "gender-select",
                    "nextQuestionId": "height-input",
                    "showNavigation": True,
                    "answer": None,
                },
                {
                    "id": "height-input",
                    "componentType": "heightSelect",
                    "type": "number",
                    "title": "您的身高",
                    "required": True,
                    "min": 0,
                    "max": 120,
                    "hasPrev": True,
                    "hasNext": True,
                    "currentIndex": 3,
                    "totalQs": 4,
                    "prevQuestionId": "q_age_picker",
                    "nextQuestionId": "weight-input",
                    "showNavigation": True,
                },
                {
                    "id": "weight-input",
                    "componentType": "weightSelect",
                    "type": "number",
                    "title": "您的体重",
                    "required": True,
                    "min": 0,
                    "max": 300,
                    "hasPrev": True,
                    "hasNext": True,
                    "currentIndex": 4,
                    "totalQs": 4,
                    "prevQuestionId": "height-input",
                    "nextQuestionId": "intro_module2",
                    "showNavigation": True,
                },
                {
                    "id": "intro_module2",
                    "type": "intro",
                    "title": "进入第二部分",
                    "required": False,
                    "description": "此部分需要您提供一些个人信息和使用时间，我们会严格保护您的隐私。",
                    "behavior": {"autoNext": True, "autoNextDelay": 1000},
                    "introImageSrc": "https://iobs.pingan.com.cn/download/pah-ows-dmz-prd/54216111800447f988bde78c3de99750",
                    "hasPrev": False,
                    "hasNext": False,
                    "currentIndex": None,
                    "totalQs": None,
                    "prevQuestionId": "height-input",
                    "nextQuestionId": "disease-history",
                    "showNavigation": False,
                },
                {
                    "id": "disease-history",
                    "type": "multipleSubchoice",
                    "title": "您是否有以下疾病？",
                    "required": False,
                    "options": [
                        {
                            "value": "hypertension",
                            "label": "高血压",
                            "subQuestion": {
                                "title": "请选择严重程度",
                                "options": [
                                    {"value": "mild", "label": "轻度"},
                                    {"value": "moderate", "label": "中度"},
                                    {"value": "severe", "label": "重度"},
                                ],
                            },
                        },
                        {
                            "value": "diabetes",
                            "label": "糖尿病",
                            "subQuestion": {
                                "title": "请选择严重程度",
                                "options": [
                                    {"value": "mild", "label": "轻度"},
                                    {"value": "moderate", "label": "中度"},
                                    {"value": "severe", "label": "重度"},
                                ],
                            },
                        },
                        {
                            "value": "hyperlipidemia",
                            "label": "高血脂",
                            "subQuestion": {
                                "title": "请选择严重程度",
                                "options": [
                                    {"value": "mild", "label": "轻度"},
                                    {"value": "moderate", "label": "中度"},
                                    {"value": "severe", "label": "重度"},
                                ],
                            },
                        },
                        {
                            "value": "cancer",
                            "label": "癌症",
                            "subQuestion": {
                                "title": "请选择严重程度",
                                "options": [
                                    {"value": "mild", "label": "轻度"},
                                    {"value": "moderate", "label": "中度"},
                                    {"value": "severe", "label": "重度"},
                                ],
                            },
                        },
                        {
                            "value": "copd",
                            "label": "慢性阻塞性肺疾病",
                            "subQuestion": {
                                "title": "请选择严重程度",
                                "options": [
                                    {"value": "mild", "label": "轻度"},
                                    {"value": "moderate", "label": "中度"},
                                    {"value": "severe", "label": "重度"},
                                ],
                            },
                        },
                        {
                            "value": "kidney_disease",
                            "label": "肾病",
                            "subQuestion": {
                                "title": "请选择严重程度",
                                "options": [
                                    {"value": "mild", "label": "轻度"},
                                    {"value": "moderate", "label": "中度"},
                                    {"value": "severe", "label": "重度"},
                                ],
                            },
                        },
                        {
                            "value": "liver_disease",
                            "label": "肝病",
                            "subQuestion": {
                                "title": "请选择严重程度",
                                "options": [
                                    {"value": "mild", "label": "轻度"},
                                    {"value": "moderate", "label": "中度"},
                                    {"value": "severe", "label": "重度"},
                                ],
                            },
                        },
                    ],
                    "hasPrev": True,
                    "hasNext": True,
                    "currentIndex": 1,
                    "totalQs": 1,
                    "prevQuestionId": "weight-input",
                    "nextQuestionId": "intro_module3",
                    "showNavigation": True,
                },
            ],
        },
        {
            "questionnaire_id": "health-goals",
            "title": "健康目标选择",
            "description": "根据评估结果推荐个性化的健康目标，供用户选择",
            "skill_name": "goal-recommendation",
            "version": 1,
            "created_by": "system",
            "updated_by": "system",
            "questions": [
                {
                    "id": "intro_module3",
                    "type": "intro",
                    "introPart": 3,
                    "documentTitle": "",
                    "introPartName": "目标",
                    "hasNext": True,
                    "totalQs": None,
                    "behavior": {"autoNext": True, "autoNextDelay": 1000},
                    "required": False,
                    "currentIndex": None,
                    "nextQuestionId": "",
                    "prevQuestionId": "disease-history",
                    "showNavigation": False,
                },
                {
                    "id": "confirmObjectives",
                    "type": "intro",
                    "componentType": "confirmObjectives",
                    "documentTitle": "运动目标",
                    "required": False,
                    "hasPrev": False,
                    "hasNext": False,
                    "currentIndex": None,
                    "totalQs": None,
                    "prevQuestionId": "disease-history",
                    "nextQuestionId": "sport_target",
                    "showNavigation": False,
                },
                {
                    "id": "sport_target1",
                    "type": "single",
                    "componentType": "image",
                    "title": "选择您的运动目标",
                    "documentTitle": "运动目标",
                    "options": [
                        {"value": "improveDiet", "label": "改善饮食", "icon": "https://iobs.pingan.com.cn/download/ehis-vitality-dmz-prd/REPSPORT202605081456198243425317"},
                        {"value": "improveSleep", "label": "改善睡眠", "icon": "https://iobs.pingan.com.cn/download/ehis-vitality-dmz-prd/REPSPORT202605081456960877442177"},
                        {"value": "loseWeight", "label": "减脂减重", "icon": "https://iobs.pingan.com.cn/download/ehis-vitality-dmz-prd/REPSPORT202605081456338243413177"},
                        {"value": "improvePhysique", "label": "改善体型", "icon": "https://iobs.pingan.com.cn/download/ehis-vitality-dmz-prd/REPSPORT202605081456418162156177"},
                        {"value": "relax", "label": "放松身心", "icon": "https://iobs.pingan.com.cn/download/ehis-vitality-dmz-prd/REPSPORT202605081456168623033817"},
                        {"value": "strengthTraining", "label": "力量训练", "icon": "https://iobs.pingan.com.cn/download/ehis-vitality-dmz-prd/REPSPORT202605081456188844998017"},
                        {"value": "exercise", "label": "运动健身", "icon": "https://iobs.pingan.com.cn/download/ehis-vitality-dmz-prd/REPSPORT202605081456394818372177"},
                    ],
                    "required": True,
                    "hasNext": True,
                    "currentIndex": 1,
                    "totalQs": 1,
                    "prevQuestionId": "disease-history",
                    "nextQuestionId": "",
                    "showNavigation": True,
                    "nextButtonText": "加油我可以",
                },
            ],
        },
    ]
