"""API DTOs module."""

from src.interface.api.dto.request import (
    ChatRequest,
    HealthAssessmentRequest,
    CreateHealthPlanRequest,
    SaveConversationRequest,
    SkillCreateRequest,
    SkillUpdateRequest,
    SkillPromptUpdateRequest,
    SkillModelConfigUpdateRequest,
    CloseConsultationRequest,
    StreamingChatRequest,
)
from src.interface.api.dto.response import (
    ChatResponse,
    VitalSignsAssessment,
    Recommendation,
    HealthProfileResponse,
    PrescriptionDetail,
    HealthPlanResponse,
    MessageResponse,
    ConsultationSummary,
    ConsultationHistoryResponse,
    SkillResponse,
    SkillListResponse,
    ErrorResponse,
    HealthResponse,
    StreamingChatChunk,
    StreamingChatStartChunk,
    StreamingChatTokenChunk,
    StreamingChatEndChunk,
    StreamingChatErrorChunk,
)

__all__ = [
    # Requests
    "ChatRequest",
    "HealthAssessmentRequest",
    "CreateHealthPlanRequest",
    "SaveConversationRequest",
    "SkillCreateRequest",
    "SkillUpdateRequest",
    "SkillPromptUpdateRequest",
    "SkillModelConfigUpdateRequest",
    "CloseConsultationRequest",
    "StreamingChatRequest",
    # Responses
    "ChatResponse",
    "VitalSignsAssessment",
    "Recommendation",
    "HealthProfileResponse",
    "PrescriptionDetail",
    "HealthPlanResponse",
    "MessageResponse",
    "ConsultationSummary",
    "ConsultationHistoryResponse",
    "SkillResponse",
    "SkillListResponse",
    "ErrorResponse",
    "HealthResponse",
    # Streaming
    "StreamingChatChunk",
    "StreamingChatStartChunk",
    "StreamingChatTokenChunk",
    "StreamingChatEndChunk",
    "StreamingChatErrorChunk",
]
